timezone: America/Sao_Paulo
collections:
  planilhas:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "planilhas"
    values:
      layout: "planilha"